-- Tabela de Fornecedores
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    contact TEXT,
    phone TEXT,
    email TEXT,
    establishment_id BIGINT REFERENCES establishments(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Fix: Garantir que a coluna 'plan' existe (Correção de Erro)
ALTER TABLE establishments ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'Starter';
ALTER TABLE establishments ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active';
ALTER TABLE establishments ADD COLUMN IF NOT EXISTS revenue NUMERIC DEFAULT 0;

-- Fix: Adicionar coluna de tema que o Settings.jsx espera
ALTER TABLE establishments ADD COLUMN IF NOT EXISTS theme_color TEXT DEFAULT '#ef4444';

-- Fix: Garantir colunas de Produtos (Evitar erro de 'image' missing)
ALTER TABLE products ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;

-- Fix: Garantir colunas de Pedidos (Mas mantendo tipo original UUID se já existir)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ordered_by UUID; -- Assumindo que originalmente era UUID
ALTER TABLE orders ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price NUMERIC;
-- (Removed forced conversion to TEXT and Policy drops to respect integrity)

-- Fix: Garantir colunas de Usuários (Evitar erro de 'password' missing)
ALTER TABLE users ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS establishment_id BIGINT;

-- Fix: Garantir que users.id tenha default UUID (Para app funcionar sem enviar ID)
-- OBS: Requer pgcrypto ou Postgres 13+. Supabase geralmente suporta gen_random_uuid().
DO $$
BEGIN
    ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Could not set default gen_random_uuid (maybe extension missing?), check manually.';
END $$;

-- Fix: Garantir colunas de Mesas
ALTER TABLE tables ADD COLUMN IF NOT EXISTS call_waiter BOOLEAN DEFAULT FALSE;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'available';

-- Tabela de Pagamentos/Caixa (Histórico de Vendas)
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES tables(id),
    amount NUMERIC NOT NULL,
    method TEXT, -- 'PIX', 'Cartão', 'Dinheiro'
    establishment_id BIGINT REFERENCES establishments(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Adicionar permissões simples (RSL) - Aberto para demo
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all on suppliers" ON suppliers;
CREATE POLICY "Enable all on suppliers" ON suppliers FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all on payments" ON payments;
CREATE POLICY "Enable all on payments" ON payments FOR ALL USING (true) WITH CHECK (true);

-- Publicar tabelas para Realtime (se necessário)
-- Publicar tabelas para Realtime (Tentativa segura)
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE suppliers;
  EXCEPTION WHEN duplicate_object THEN
    -- Table already in publication, ignore
    RAISE NOTICE 'Table suppliers already in publication';
  END;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE payments;
  EXCEPTION WHEN duplicate_object THEN
    -- Table already in publication, ignore
    RAISE NOTICE 'Table payments already in publication';
  END;
END $$;
