-- SCHEMA V2 - CLEAN SLATE
-- Atenção: Isso apagará TODOS os dados existentes.

-- 1. Limpeza
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS establishment_staff CASCADE;
DROP TABLE IF EXISTS establishments CASCADE;
DROP TABLE IF EXISTS b2b_users CASCADE;
DROP TABLE IF EXISTS b2c_users CASCADE;
DROP TABLE IF EXISTS users CASCADE; -- Dropping old legacy table

-- 2. Extensions (Garantir UUIDs)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 3. Users & Auth Split
-- Usuários B2B (Donos, Gerentes, Garçons, Cozinha)
CREATE TABLE b2b_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE, -- Email opcional para garçons simples, mas obrigatório para donos
    password_hash TEXT, -- Simplificado para Demo
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Usuários B2C (Clientes do App Consagrado)
CREATE TABLE b2c_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Structure (Multi-Tenant)
CREATE TABLE establishments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id UUID REFERENCES b2b_users(id) NOT NULL,
    theme_color TEXT DEFAULT '#ef4444',
    theme_secondary_color TEXT DEFAULT '#f59e0b', -- Cor Secundária (Laranja Padrão)
    theme_background_color TEXT DEFAULT '#09090b', -- Cor de Fundo (Dark Standard)
    cover_image TEXT,
    settings JSONB DEFAULT '{}', -- Para configurações flexíveis (ex: ordem das abas)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabela de Vínculo: Funcionários <-> Estabelecimentos
CREATE TABLE establishment_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES b2b_users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('manager', 'waiter', 'kitchen')),
    access_pin TEXT, -- PIN específico para este local (ex: Luigi tem PIN 1234 aqui e 9999 lá)
    UNIQUE(establishment_id, user_id)
);

-- 5. Resources (Scoped by Establishment)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    category TEXT,
    description TEXT,
    image TEXT,
    available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE NOT NULL,
    number INT NOT NULL,
    code TEXT NOT NULL, -- Format: AA0000 (Ex: IM0001)
    status TEXT DEFAULT 'available', -- available, occupied
    call_waiter BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(establishment_id, code)
);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    contact TEXT,
    phone TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Operations (Orders & Sales)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE NOT NULL,
    table_id BIGINT REFERENCES tables(id),
    product_id BIGINT REFERENCES products(id),
    
    -- Quem pediu? Pode ser Staff ou Cliente
    ordered_by_staff_id UUID REFERENCES b2b_users(id),
    ordered_by_customer_id UUID REFERENCES b2c_users(id),
    author_name TEXT, -- Snapshot do nome para facilitar display

    name TEXT, -- Snapshot do produto
    price NUMERIC, -- Snapshot do preço
    quantity INT DEFAULT 1,
    status TEXT DEFAULT 'pending', -- pending, delivered, paid
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT REFERENCES establishments(id) ON DELETE CASCADE NOT NULL,
    table_id BIGINT REFERENCES tables(id),
    amount NUMERIC NOT NULL,
    method TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Realtime Enablement
ALTER PUBLICATION supabase_realtime ADD TABLE tables;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE payments;
