-- 1. Clean up (optional, be careful)
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS establishments;
DROP TABLE IF EXISTS users;

-- 2. Create Tables

CREATE TABLE establishments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    plan TEXT DEFAULT 'Starter',
    status TEXT DEFAULT 'Active',
    revenue NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    category TEXT,
    description TEXT,
    image TEXT, -- Emoji or URL
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INT NOT NULL,
    status TEXT DEFAULT 'available', -- 'available', 'occupied'
    call_waiter BOOLEAN DEFAULT FALSE,
    establishment_id BIGINT REFERENCES establishments(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT REFERENCES tables(id),
    product_id BIGINT REFERENCES products(id),
    name TEXT, -- Snapshot of product name
    price NUMERIC, -- Snapshot of price
    quantity INT DEFAULT 1,
    status TEXT DEFAULT 'pending', -- 'pending', 'delivered'
    ordered_by TEXT, -- 'Garçom' or Customer Name
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    password TEXT, -- Plain text for MVP demo only
    role TEXT, -- 'super', 'owner', 'waiter', 'client'
    establishment_id BIGINT REFERENCES establishments(id),
    pin TEXT -- For waiters
);

-- 3. Seed Mock Data

INSERT INTO establishments (name, plan, status, revenue) VALUES
('Bar do Zé', 'Pro', 'Active', 45200.00),
('Balada Night', 'Enterprise', 'Active', 128500.00);

INSERT INTO products (name, price, category, description, image) VALUES
('Cerveja Heineken 600ml', 18.00, 'Cervejas', 'Gelada trincando', '🍺'),
('Caipirinha Limão', 25.00, 'Drinks', 'Com cachaça artesanal', '🍋'),
('Batata Frita', 22.00, 'Petiscos', 'Com cheddar e bacon', '🍟');

INSERT INTO tables (number, status, establishment_id) VALUES
(1, 'available', 1),
(2, 'occupied', 1),
(3, 'available', 1),
(4, 'available', 1);

INSERT INTO users (name, email, password, role, establishment_id, pin) VALUES
('Super Admin', 'admin@consagrado.com', '123', 'super', NULL, NULL),
('Dono do Bar', 'owner@bardozé.com', '123', 'owner', 1, NULL),
('Garçom João', NULL, NULL, 'waiter', 1, '1234');

-- 4. Enable Realtime (Crucial for Waiter App)
alter publication supabase_realtime add table tables;
alter publication supabase_realtime add table orders;
